name: Change shell
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - shell: bash # シェルにbashを指定
        run: echo "${SHELL}"
      - shell: python # シェルにpythonを指定
        run: |
          import os
          print(os.environ['PATH'])